name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Lint errors ko bypass karne ke liye -x lint commands add kiye hain
    - name: Build Release APK
      run: ./gradlew assembleRelease -x lint -x lintVitalRelease

    - name: Sign Release APK
      run: |
        keytool -genkey -v -keystore temp.keystore -alias tempkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=EverDialer"
        APKSIGNER=$(find $ANDROID_HOME/build-tools -name "apksigner" | sort | tail -1)
        # Nayi line: Folder me jo bhi APK ho usko automatic dhoondh lo
        APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
        $APKSIGNER sign --ks temp.keystore --ks-pass pass:android --key-pass pass:android "$APK_PATH"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Ever-Dialer-Fast-Release
        path: app/build/outputs/apk/release/*.apk
        
